// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeQUeCON3_2JgF6lDnaNfmcwl3PO8M6yU',
    appId: '1:159972411554:web:aa2c3a53c5828771e7affb',
    messagingSenderId: '159972411554',
    projectId: 'islamic-app-fc619',
    authDomain: 'islamic-app-fc619.firebaseapp.com',
    storageBucket: 'islamic-app-fc619.appspot.com',
    measurementId: 'G-33GCEHYSC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZhaV-sczAXzKCQE1KQwfatOYoM1bODI',
    appId: '1:159972411554:android:d9e015fa20e5b24ae7affb',
    messagingSenderId: '159972411554',
    projectId: 'islamic-app-fc619',
    storageBucket: 'islamic-app-fc619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnz__o0IrcKkeWSMywkISpBedFzKDIqk',
    appId: '1:159972411554:ios:8518a60aef2d3d56e7affb',
    messagingSenderId: '159972411554',
    projectId: 'islamic-app-fc619',
    storageBucket: 'islamic-app-fc619.appspot.com',
    iosBundleId: 'com.example.islamicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPnz__o0IrcKkeWSMywkISpBedFzKDIqk',
    appId: '1:159972411554:ios:488e55e67f5d8397e7affb',
    messagingSenderId: '159972411554',
    projectId: 'islamic-app-fc619',
    storageBucket: 'islamic-app-fc619.appspot.com',
    iosBundleId: 'com.example.islamicApp.RunnerTests',
  );
}
